# Generated by Django 2.0.13 on 2019-06-16 06:52

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_agentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='email',
            field=models.EmailField(help_text='Active email address', max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='name',
            field=models.CharField(help_text='Full name as in Passport', max_length=40, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='nationality',
            field=models.CharField(help_text='As described in passport', max_length=30, verbose_name='nationality'),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Active phone number', max_length=128, verbose_name='Phone number'),
        ),
    ]
