# Generated by Django 2.0.13 on 2019-06-16 08:31

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190616_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.Country', verbose_name='Agent Present Country'),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Agent Created'),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='email',
            field=models.EmailField(help_text='Active email address', max_length=254, unique=True, verbose_name='Agent Email Address'),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='name',
            field=models.CharField(help_text='Full name as in Passport', max_length=40, verbose_name='Agent Full Name'),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='nationality',
            field=models.CharField(help_text='As described in passport', max_length=30, verbose_name='Agent Nationality'),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='passport_copy',
            field=models.FileField(help_text='Scanned document', upload_to='agents/passport/', verbose_name='Agent Passport Copy'),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Active phone number', max_length=128, verbose_name='Agent Phone Number'),
        ),
    ]
