# Generated by Django 2.0.13 on 2019-06-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190616_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='passport_copy',
            field=models.FileField(help_text='Scanned document', upload_to='agents/passport/%Y/%m/%d/', verbose_name='Agent Passport Copy'),
        ),
    ]
