# Generated by Django 2.0.13 on 2019-09-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_agentinterestrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentinterestrate',
            name='name',
            field=models.CharField(default='', editable=False, max_length=30, verbose_name='Interest Rate Name'),
        ),
    ]
