# Generated by Django 2.0.13 on 2019-09-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_agentinterestrate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentinterestrate',
            name='name',
            field=models.CharField(default='', max_length=30, verbose_name='Interest Rate Name'),
        ),
    ]
